version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: planti
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" 
      - "8025:8025" 
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/planti
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM: noreply@planti.app
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - mailhog
    command: >
      sh -c "npm install &&
             npm run dev"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: >
      sh -c "npm install --legacy-peer-deps &&
             npm run dev"
    restart: unless-stopped

volumes:
  postgres_data: 